import Head from 'next/head'
import Image from 'next/image'
import Navbar from '@/components/Navbar/Navbar'


export default function Home() {
  return (
    <>
      {/*Head component from NextJs*/}
      <Head>
        <title>Advanced Shopping Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/*The content of the home page is empty for now, containing only
        the Navbar, because the target in this development is just the 
        store cart functionality*/}
        <Navbar />
      </main>
    </>
  )
}
